export const jobTechnologies = [
  { value: "angular", label: "Angular" },
  { value: "aws", label: "AWS" },
  { value: "c#", label: "C#" },
  { value: "c++", label: "C++" },
  { value: "django", label: "Django" },
  { value: "docker", label: "Docker" },
  { value: "dotnet", label: ".NET" },
  { value: "express", label: "Express" },
  { value: "firebase", label: "Firebase" },
  { value: "flutter", label: "Flutter" },
  { value: "git", label: "Git" },
  { value: "github", label: "GitHub" },
  { value: "go", label: "Go" },
  { value: "graphql", label: "GraphQL" },
  { value: "java", label: "Java" },
  { value: "javascript", label: "JavaScript" },
  { value: "jest", label: "Jest" },
  { value: "jwt", label: "JWT" },
  { value: "kubernetes", label: "Kubernetes" },
  { value: "laravel", label: "Laravel" },
  { value: "mongodb", label: "MongoDB" },
  { value: "mysql", label: "MySQL" },
  { value: "nestjs", label: "NestJS" },
  { value: "nextjs", label: "Next.js" },
  { value: "nodejs", label: "Node.js" },
  { value: "nuxt", label: "Nuxt" },
  { value: "php", label: "PHP" },
  { value: "postgresql", label: "PostgreSQL" },
  { value: "prisma", label: "Prisma" },
  { value: "python", label: "Python" },
  { value: "react", label: "React" },
  { value: "react-native", label: "React Native" },
  { value: "redis", label: "Redis" },
  { value: "ruby", label: "Ruby" },
  { value: "spring", label: "Spring" },
  { value: "supabase", label: "Supabase" },
  { value: "tailwindcss", label: "Tailwind CSS" },
  { value: "tanstack-query", label: "TanStack Query" },
  { value: "typescript", label: "TypeScript" },
  { value: "vite", label: "Vite" },
  { value: "vue", label: "Vue" },
  { value: "zustand", label: "Zustand" },
];
